### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jrodl3r** [jrodl3r/frame#1]
## Outline
- [ ] Chromeless viewport window (chrome only visible on hover)
- [ ] Only visible element on each tab is a centered URL bar
- [ ] Icon-only tabs open (cmd+t / cmd-enter on URL bar) and close (on cmd+x)
- [ ] App control bar + tab bar (if >1 tab) visible on hover
